parameters:
    mailer_user: 'admin@example.com'
framework:
    translator: ~
    templating:
        engines: ['twig', 'php']    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Usuario
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
